--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -469,6 +469,7 @@
 obj-y += display/
 
 obj-$(CONFIG_IO_FOOTPRINT) += io_footprint.o
+obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
 
 #PWR2_ADD, @CPU Sniffer: CPU usage statistics.
 obj-y += htc_cpu_usage_stats.o
